### ISSUE TITLE
Jsystem runner loop presentation is wrong

### ISSUE THREAD

**Issue by dayaDagan** [Top-Q/difido-reports#241]
Jsystme runner 6.1.12-SNAPSHOT when run in scenario tests in loop (1..10) all tests enter to 1 loop and present as flat run (only loop num 1, and no loop num 2  etc.) .

![Capture](https://user-images.githubusercontent.com/67860766/86531213-04b61580-bec8-11ea-9c95-f7afbf32c4b0.PNG)

**Comment by itaiag** [comment]
![Screenshot from 2020-07-12 11-08-11](https://user-images.githubusercontent.com/1835335/87241889-0e8fc980-c430-11ea-86e9-1d25e45d6149.png)

This is not reproducible in the latest JSystem/Difido versions. Maybe this is because the **security_all_tests** scenario is holding all the tests and it is the one that actually executed 10 times?
